-- Additional tables for delivery man inventory check and permission system

-- Product permission requests table
CREATE TABLE product_permission_requests (
    id INT AUTO_INCREMENT PRIMARY KEY,
    delivery_man_id INT NOT NULL,
    supplier_name VARCHAR(200) NOT NULL,
    product_code VARCHAR(100) NOT NULL,
    product_name VARCHAR(200) NOT NULL,
    category VARCHAR(100) NOT NULL,
    mrp DECIMAL(10,2) NOT NULL,
    selling_price DECIMAL(10,2) NOT NULL,
    quantity INT NOT NULL,
    invoice_image VARCHAR(500), -- Path to uploaded invoice image
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
    accountant_id INT NULL,
    review_notes TEXT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP NULL,
    FOREIGN KEY (delivery_man_id) REFERENCES users(id),
    FOREIGN KEY (accountant_id) REFERENCES users(id)
);

-- Inventory transactions table for tracking all inventory changes
CREATE TABLE inventory_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    product_id INT NOT NULL,
    transaction_type ENUM('delivery', 'restock', 'adjustment', 'return') NOT NULL,
    quantity_change INT NOT NULL, -- Positive for additions, negative for subtractions
    booking_id INT NULL, -- For delivery transactions
    request_id INT NULL, -- For restock from delivery requests
    notes TEXT NULL,
    created_by INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (booking_id) REFERENCES bookings(id),
    FOREIGN KEY (request_id) REFERENCES product_permission_requests(id),
    FOREIGN KEY (created_by) REFERENCES users(id)
);

-- Add index for better performance
CREATE INDEX idx_status_delivery_man ON product_permission_requests(status, delivery_man_id);
CREATE INDEX idx_status_accountant ON product_permission_requests(status, accountant_id);
CREATE INDEX idx_inventory_product ON inventory_transactions(product_id, transaction_type);
CREATE INDEX idx_inventory_booking ON inventory_transactions(booking_id);

-- Add product_code column to products table if it doesn't exist
-- (This will be used for unique product identification)
ALTER TABLE products ADD COLUMN IF NOT EXISTS product_code VARCHAR(100) UNIQUE AFTER sku;

-- Note: New products will get automatic product codes generated by the system
-- No need to copy SKU codes anymore as the system now auto-generates unique codes
